INSERT INTO public."Cards" (id, packid, type, content) VALUES (1, 1, 'positive', 'Fiercely loyal');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (2, 1, 'positive', 'Believes you are the most attractive person they''ve ever seen');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (3, 1, 'positive', 'Trusting');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (4, 1, 'positive', 'Respectful');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (5, 1, 'positive', 'Honest');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (6, 1, 'positive', 'Patient');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (7, 1, 'positive', 'Reliable');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (8, 1, 'positive', 'Courteous');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (9, 1, 'positive', 'Funniest person in the world');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (10, 1, 'positive', 'Affectionate');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (11, 1, 'positive', 'Good listener');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (12, 1, 'positive', 'Supportive');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (13, 1, 'positive', 'Generous');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (14, 1, 'positive', 'Driven');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (15, 1, 'positive', 'Perfect communicator');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (16, 1, 'positive', 'Always makes time for you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (17, 1, 'positive', 'Always gives you perfect gifts');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (18, 1, 'positive', 'Perfect amount of physical affection');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (19, 1, 'positive', 'Adventurous');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (20, 1, 'positive', 'Loves you unconditionally');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (21, 1, 'positive', 'In touch with their feelings');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (22, 1, 'positive', 'Your parents love them');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (23, 1, 'positive', 'Your friends and enemies are jealous');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (24, 1, 'positive', 'Owns a magic carpet');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (25, 1, 'positive', 'Volunteers with elderly people');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (26, 1, 'positive', 'Loves dogs');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (27, 1, 'positive', 'Loves cats');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (28, 1, 'positive', 'Loves theater');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (29, 1, 'positive', 'Animal shelter volunteer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (30, 1, 'positive', 'Travels a lot');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (31, 1, 'positive', 'Really into wine');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (32, 1, 'positive', 'Loves video games');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (33, 1, 'positive', 'Has front row tickets to every concert');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (34, 1, 'positive', 'Has front row tickets to every sporting event');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (35, 1, 'positive', 'Loves sports');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (36, 1, 'positive', 'Loves the outdoors');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (37, 1, 'positive', 'Loves staying in');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (38, 1, 'positive', 'Owns your favorite museum');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (39, 1, 'positive', 'Same favorite movies');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (40, 1, 'positive', 'Same favorite books');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (41, 1, 'positive', 'Same favorite foods');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (42, 1, 'positive', 'Same favorite music');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (43, 1, 'positive', 'Lives off the grid');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (44, 1, 'positive', 'Loves children');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (45, 1, 'positive', 'Millionaire');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (46, 1, 'positive', 'Most physically attractive person you have ever seen');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (47, 1, 'positive', 'Owns a vineyard');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (48, 1, 'positive', 'Owns an adorable coffee shop');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (49, 1, 'positive', 'Lives on 100 beachfront acres');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (50, 1, 'positive', 'Owns a solid gold private jet');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (51, 1, 'positive', 'Has a magic bag that contains unlimited cheese');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (52, 1, 'positive', 'Owns a 500-foot yacht');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (53, 1, 'positive', 'Owns an island in the Bahamas');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (54, 1, 'positive', 'Owns one of every car');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (55, 1, 'positive', 'Owns 100 horses');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (56, 1, 'positive', 'Owns your favorite sports team');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (57, 1, 'positive', 'Owns a penthouse suite in your favorite city');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (58, 1, 'positive', 'Gives billions to your favorite charity');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (59, 1, 'positive', 'Owns a time machine');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (60, 1, 'positive', 'Lives in a castle');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (61, 1, 'positive', 'Has the best hair ever');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (62, 1, 'positive', 'Owns a unicorn');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (63, 1, 'positive', 'Genius-level IQ');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (64, 1, 'positive', 'Owns a successful startup');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (66, 1, 'positive', 'Can get you both into literally anywhere');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (67, 1, 'positive', 'You''ll never have to work while you date them');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (68, 1, 'positive', 'You''ll never get sick while you date them');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (69, 1, 'positive', 'You literally will not age while you date them');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (70, 1, 'positive', 'Always smells like ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (71, 1, 'positive', 'Looks exactly like ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (72, 1, 'positive', 'Has a mansion in ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (73, 1, 'positive', 'Speaks every romantic language');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (74, 1, 'positive', 'Drives a ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (75, 1, 'positive', 'Is a professional ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (76, 1, 'positive', 'Owns a ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (77, 1, 'positive', 'Knows everything about ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (78, 1, 'positive', 'Volunteers for ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (79, 1, 'positive', 'You will never gain weight while you date them');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (80, 1, 'positive', 'Has the voice of an angel');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (81, 1, 'positive', 'Owns a goose that lays designer clothing');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (82, 1, 'positive', 'Has a cellar full of ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (83, 1, 'positive', 'Professional surfer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (84, 1, 'positive', 'Rocket scientist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (85, 1, 'positive', 'Model');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (86, 1, 'positive', 'Professional football player');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (87, 1, 'positive', 'Famous artist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (88, 1, 'positive', 'College English professor');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (89, 1, 'positive', 'Firefighter');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (90, 1, 'positive', 'Astronaut');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (91, 1, 'positive', 'President');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (92, 1, 'positive', 'Rodeo champion');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (93, 1, 'positive', 'Professional wrestler');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (94, 1, 'positive', 'Famous movie star');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (95, 1, 'positive', 'Famous musician');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (96, 1, 'positive', 'Famous rapper');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (98, 1, 'positive', 'Supermodel');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (99, 1, 'positive', 'Professional chef');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (100, 1, 'positive', 'Is never gonna give you up / Let you down / Run around / Or desert you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (101, 1, 'positive', 'World''s best hair stylist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (102, 1, 'positive', 'Brain surgeon');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (103, 1, 'positive', 'Lawyer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (104, 1, 'positive', 'CEO');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (105, 1, 'positive', 'World''s best advertising executive');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (106, 1, 'positive', 'Airline pilot');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (107, 1, 'positive', 'Marine');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (108, 1, 'positive', 'Spin instructor');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (109, 1, 'positive', 'Bestselling author');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (110, 1, 'positive', 'YouTube celebrity');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (111, 1, 'positive', 'Lumberjack');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (112, 1, 'positive', 'Organic farmer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (113, 1, 'positive', 'Stunt double');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (114, 1, 'positive', 'Park ranger');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (115, 1, 'positive', 'Ski instructor');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (116, 1, 'positive', 'Photographer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (117, 1, 'positive', 'Famous fashion designer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (118, 1, 'positive', 'Is royalty');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (119, 1, 'positive', 'Is a genie');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (120, 1, 'positive', 'World champion ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (121, 1, 'positive', 'World champion hunter');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (122, 1, 'positive', 'Won the medal of honor');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (123, 1, 'positive', 'Was on the news for rescuing a kitten');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (124, 1, 'positive', 'Best-smelling person in the world');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (125, 1, 'positive', 'Yoga instructor');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (126, 1, 'positive', 'The hot barista');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (127, 1, 'positive', 'Has an 8-pack');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (128, 1, 'positive', 'Olympic gymnast');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (129, 1, 'positive', 'Pick an actor/actress');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (130, 1, 'positive', 'Never arrives prematurely');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (131, 1, 'positive', 'Loves to cuddle');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (133, 1, 'positive', 'Has the most attractive ??? you''ve ever seen');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (134, 1, 'positive', 'The lead singer of your favorite band');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (135, 1, 'positive', 'Beautiful eyes');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (136, 1, 'positive', 'Completely blind to all of your flaws');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (137, 1, 'positive', 'Spontaneous and fun');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (138, 1, 'positive', 'Makes you feel secure');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (139, 1, 'positive', 'Has the hottest friends');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (140, 1, 'positive', 'Has a twin');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (141, 1, 'positive', 'Life is the true story that ??? is based on');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (142, 1, 'positive', 'Can fly');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (143, 1, 'positive', 'Superhero');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (144, 1, 'positive', 'Loves to laugh');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (145, 1, 'positive', 'Makes scented candles');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (146, 1, 'positive', 'Loves the ''80s');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (147, 1, 'positive', 'Cooks all your favorite foods');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (148, 1, 'positive', 'Knows all the words to your favorite children''s TV theme songs');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (149, 1, 'positive', 'Never blames you for anything');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (150, 1, 'positive', 'Can get you free drinks forever at any bar in the world');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (151, 1, 'positive', 'Creates shelters for the homeless');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (152, 1, 'positive', 'Their kisses cure cancer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (153, 1, 'positive', 'Is a great conversationalist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (154, 1, 'positive', 'Gives the best hugs');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (156, 1, 'positive', 'Is a merperson');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (157, 1, 'positive', 'Always knows how to stop you from crying');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (158, 1, 'positive', 'Can multiply themselves');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (159, 1, 'positive', 'An amazing dancer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (160, 1, 'positive', 'Always defends you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (161, 1, 'positive', 'Can get you a table at any 5-star restaurant any time any place');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (162, 1, 'positive', 'Can fire your most hated co-worker or boss');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (163, 1, 'positive', 'Their farts smell like flowers');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (164, 1, 'positive', 'Never farts');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (165, 1, 'positive', 'Their morning breath smells like fresh-baked cookies');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (166, 1, 'positive', 'Owns Mars');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (167, 1, 'positive', 'Is a night person and a morning person');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (168, 1, 'positive', 'Loves their job');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (169, 1, 'positive', 'Has all the same hobbies as you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (170, 1, 'positive', 'Can talk to animals');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (171, 1, 'positive', 'Owns real dinosaurs');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (172, 1, 'positive', 'Gives great massages');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (173, 1, 'negative', 'Thinks they''re a Jedi');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (174, 1, 'negative', 'Civil War reenactor');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (175, 1, 'negative', 'Super super racist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (176, 1, 'negative', 'Sexist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (177, 1, 'negative', 'Really stupid');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (178, 1, 'negative', 'Owes the government one million dollars');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (179, 1, 'negative', 'Death row inmate');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (181, 1, 'negative', 'Thinks you''re ugly');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (182, 1, 'negative', 'Their pet name for you is trash bag');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (183, 1, 'negative', 'Is always covered in ants');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (184, 1, 'negative', 'Really really hates children');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (185, 1, 'negative', 'Only speaks in horrible puns');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (186, 1, 'negative', 'Is a merperson');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (187, 1, 'negative', 'Sees the ghost of everyone who has ever died');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (191, 1, 'negative', 'Is a train wreck');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (192, 1, 'negative', 'Backseat driver');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (193, 1, 'negative', 'Reads over your shoulder (out loud)');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (194, 1, 'negative', 'Is six years old');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (195, 1, 'negative', 'Only speaks in sarcasm');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (196, 1, 'negative', 'Farts every time they kiss you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (197, 1, 'negative', 'Kicks every animal they see');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (198, 1, 'negative', 'Worst-smelling person in the world');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (199, 1, 'negative', 'Amateur cannibal');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (200, 1, 'negative', 'Dabbles in torture');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (201, 1, 'negative', 'Uses the word chillax in every sentence');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (202, 1, 'negative', 'Body type: Dumpster');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (203, 1, 'negative', 'Has a permanent fedora');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (204, 1, 'negative', 'Basic');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (205, 1, 'negative', 'Spends every date using dating apps');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (206, 1, 'negative', 'Literally can''t make decisions');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (207, 1, 'negative', 'Has to pee every five minutes for five minutes');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (208, 1, 'negative', 'Sold your pets on Craigslist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (209, 1, 'negative', 'Only speaks in yelling');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (210, 1, 'negative', 'Doesn''t know the difference between your and you''re');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (211, 1, 'negative', 'Only speaks in business buzzwords');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (212, 1, 'negative', 'Eats crayons');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (213, 1, 'negative', 'Has a dozen kids from a dozen partners');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (214, 1, 'negative', 'Is wanted in every state except Florida / (Because Florida doesn''t want them)');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (215, 1, 'negative', 'Is a hobbit');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (216, 1, 'negative', 'Has nineteen kids and counting');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (217, 1, 'negative', 'Is building an ark');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (219, 1, 'negative', 'Will only eat if you play airplane with their food');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (220, 1, 'negative', 'Literally always on a Segway');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (221, 1, 'negative', 'Cries themself to sleep every night');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (222, 1, 'negative', 'Takes you to ??? on the first date');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (223, 1, 'negative', 'Is Nickelback');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (224, 1, 'negative', 'Counts your calories');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (225, 1, 'negative', 'Can''t keep a job longer than twenty minutes');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (226, 1, 'negative', 'Hair is transplanted from cadaver butts');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (227, 1, 'negative', 'Looks and smells just like your dad');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (228, 1, 'negative', 'Throws up every time they see your face');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (229, 1, 'negative', 'Is your clone');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (231, 1, 'negative', 'Yawns every time you start a sentence');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (232, 1, 'negative', 'First name is Poop');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (233, 1, 'negative', 'College nickname: Puke Crotch');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (234, 1, 'negative', 'Still in fourth grade');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (235, 1, 'negative', 'Teleports to the North Pole every time they say the word love');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (237, 1, 'negative', 'Takes you to couples therapy on the first date');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (238, 1, 'negative', 'Only speaks in boy band lyrics');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (239, 1, 'negative', 'Hits on every server');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (240, 1, 'negative', 'Has never spelled a word correctly');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (241, 1, 'negative', 'Collects human skulls / Says they''re practically free!');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (242, 1, 'negative', 'Steals something from every store they enter');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (243, 1, 'negative', 'Compulsive liar');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (244, 1, 'negative', 'Is eligible for the Make-A-Wish Foundation');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (245, 1, 'negative', 'Calls you by exe''s name / Every time');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (246, 1, 'negative', 'Always wearing a Bluetooth headset');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (247, 1, 'negative', 'Is the person you hated the most in high school / and literally hasn''t changed');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (248, 1, 'negative', 'Posts all of your texts and emails online');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (249, 1, 'negative', '3-foot fingernails');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (250, 1, 'negative', 'Keeps asking if your best friend is down');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (251, 1, 'negative', 'Only communicates with you via fax');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (252, 1, 'negative', 'Only speaks Klingon');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (253, 1, 'negative', 'Literally won''t stop talking about their mother');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (254, 1, 'negative', 'Sleep-puncher');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (255, 1, 'negative', 'Has scissor hands');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (256, 1, 'negative', 'Describes all food as yummy yummers');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (258, 1, 'negative', 'Won''t allow wi-fi in the house');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (259, 1, 'negative', 'Refuses to wash hands');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (260, 1, 'negative', 'Celibate');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (261, 1, 'negative', 'Has plexiglass cheeks so that you can see inside their mouth');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (262, 1, 'negative', 'Responds to everything to say with that''s what she said');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (263, 1, 'negative', 'Isn''t potty trained');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (264, 1, 'negative', 'Is a serial killer');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (265, 1, 'negative', 'Only speaks in Disney song lyrics');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (266, 1, 'negative', 'Still uses a flip phone');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (267, 1, 'negative', 'Has two other spouses');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (268, 1, 'negative', 'Only eats deep-fried food');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (269, 1, 'negative', 'Lives off the grid');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (270, 1, 'negative', 'Tries to pay for everything with farm animals');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (271, 1, 'negative', 'Never stops playing the ukulele');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (272, 1, 'negative', 'Regularly hosts tea parties for dolls');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (273, 1, 'negative', 'Is the oldest living person');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (274, 1, 'negative', 'Constantly taking selfies');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (275, 1, 'negative', 'Has ??? for hands');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (276, 1, 'negative', 'Says Can you not while you cry at a funeral');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (277, 1, 'negative', 'Adds you as an emergency contact on the first date');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (278, 1, 'negative', 'Literally only talks about themselves');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (279, 1, 'negative', 'Only responds to texts with k');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (280, 1, 'negative', 'Is related to you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (281, 1, 'negative', 'Incapable of all emotion');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (282, 1, 'negative', 'Is actually two children stacked on top of each other in a trench coat');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (284, 1, 'negative', 'Tells you to calm down after everything you say');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (285, 1, 'negative', 'You are allergic to them');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (287, 1, 'negative', 'Is totally married');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (289, 1, 'negative', 'Refers to their genitals as their no-no');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (290, 1, 'negative', 'Rigged to a time bomb');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (291, 1, 'negative', 'Is a zombie');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (292, 1, 'negative', 'Conveniently forgets wallet every date night / Always has ID though');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (293, 1, 'negative', 'Calls you a 4 to your face');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (294, 1, 'negative', 'Steals locks of your hair');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (296, 1, 'negative', 'Repeats your jokes but louder');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (297, 1, 'negative', 'Compulsively licks doorknobs');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (298, 1, 'negative', 'Physically incapable of asking a question');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (299, 1, 'negative', 'Jealous of your pet');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (300, 1, 'negative', 'Afraid of sunlight');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (301, 1, 'negative', 'Speaks with a constantly changing foreign accent');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (302, 1, 'negative', 'Literally always drunk');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (303, 1, 'negative', 'Brings ex to first date');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (304, 1, 'negative', 'Brings mom to first date');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (305, 1, 'negative', 'Burps and blows in your face');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (307, 1, 'negative', 'Literally never stops talking');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (308, 1, 'negative', 'Constantly plotting to kill you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (309, 1, 'negative', 'Open mouth kisses their pets');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (310, 1, 'negative', 'Immediately tries to kill you with a fork');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (311, 1, 'negative', 'Super clingy');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (313, 1, 'negative', 'Literally won''t talk to you if you''re part of the wrong Hogwarts house');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (314, 1, 'negative', 'Greets you with a headbutt');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (316, 1, 'negative', 'Always picking their nose');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (317, 1, 'negative', 'Only speaks in hashtags');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (318, 1, 'negative', 'Demands to pop all of your zits for you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (319, 1, 'negative', 'Recites all the lines from Titanic in their sleep');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (320, 1, 'negative', 'Narrates everything they do out loud');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (321, 1, 'negative', 'Puts air quotes around every word they say');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (322, 1, 'negative', 'Knocks things out of strangers'' hands while walking down the street');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (323, 1, 'negative', 'Charges you a quarter every time you say a curse word');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (324, 1, 'negative', 'Is dead');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (326, 1, 'negative', 'Talks dirty to all of their food');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (327, 1, 'negative', 'Has the names of all of their exes tattooed on their face');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (328, 1, 'negative', 'Only wears clothing made of human hair');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (329, 1, 'negative', 'Wears diapers because it''s more convenient');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (330, 1, 'negative', 'Can only speak in lines from ???');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (331, 1, 'negative', 'Only laughs at their own jokes');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (332, 1, 'negative', 'Keeps changing the subject to talk about how not racist they are');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (333, 1, 'negative', 'Just got out of prison / but won''t tell you what they were in for');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (335, 1, 'negative', 'Doesn''t think women should vote');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (336, 1, 'negative', 'Has been stalking you since middle school');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (337, 1, 'negative', 'Is 40 years older than they were in their profile picture');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (339, 1, 'negative', 'Winks at you after everything they say ;)');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (340, 1, 'negative', 'Swears you look exactly like their sister / But says that''s a good thing');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (342, 1, 'negative', 'Wears a backpack full of ??? during sex');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (343, 1, 'negative', 'Men''s rights activist');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (345, 1, 'negative', 'Ends every conversation with you''re dismissed');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (346, 1, 'negative', 'Sells home-made pubic hair wigs');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (347, 1, 'negative', 'Still really into Myspace');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (349, 1, 'negative', 'Can only have conversations through puppets');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (350, 1, 'negative', 'Always wears a luchador mask');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (351, 1, 'negative', 'Has half a beard / Absolutely refuses to shave');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (352, 1, 'negative', 'Swears they''re eighteen');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (353, 1, 'negative', 'Yells ear muffs! whenever they hear a bad word');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (354, 1, 'negative', 'Amateur vigilante');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (355, 1, 'negative', 'Won''t stop juggling');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (356, 1, 'negative', 'Resting dumb face');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (358, 1, 'negative', 'Talks exclusively in emojis');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (359, 1, 'negative', 'Refuses to delete online dating profile');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (361, 1, 'negative', 'Can only eat out of someone else''s hand');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (363, 1, 'negative', 'Refuses to cover face while sneezing');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (364, 1, 'negative', 'Refuses to look up from phone');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (365, 1, 'negative', 'Keeps talking about someone who looks just like you / Only better!');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (366, 1, 'negative', 'Thinks Twilight deserved an Oscar');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (367, 1, 'negative', 'Is afraid of stoplights');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (368, 1, 'negative', 'Doesn''t understand your jokes');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (371, 1, 'negative', 'Is a revenge porn mogul');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (372, 1, 'negative', 'Live-tweets your entire date');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (374, 1, 'negative', 'For as long as you date them all your friends will hate you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (375, 1, 'negative', 'Always dresses like a clown');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (376, 1, 'negative', 'Constantly freestyles / Badly');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (378, 1, 'negative', 'Only speaks in motivational quotes');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (379, 1, 'negative', 'The two halves of their face don''t match / Both are attractive but look totally different');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (380, 1, 'negative', 'Doesn''t know or understand any word that starts with the letter D');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (381, 1, 'negative', 'Only has eyes for you / They literally can''t see anyone in the world except you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (382, 1, 'negative', 'Has a superpower / It''s seeing through people''s clothes');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (383, 1, 'negative', 'Always takes the joke three steps too far');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (384, 1, 'negative', 'Is on every fad diet at the same time');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (385, 1, 'negative', 'Calls their pets their children');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (386, 1, 'negative', 'Static shocks you every time you touch');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (387, 1, 'negative', 'Is allergic to all of your favorite foods');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (388, 1, 'negative', 'Says like, like all the time');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (389, 1, 'negative', 'Literally has the face of a pug');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (390, 1, 'negative', 'Begins every sentence with actually');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (391, 1, 'negative', 'Lives in a bedroom with eight dudes / Including one named Jug');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (392, 1, 'negative', 'Doesn''t like music... / any of it');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (393, 1, 'negative', 'Thinks they''re smarter than you');
INSERT INTO public."Cards" (id, packid, type, content) VALUES (394, 1, 'negative', 'As long as you date them you can only eat food off the dollar menu');
